from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(max_length=100),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(),
                ),
                (
                    "message",
                    models.TextField(),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict),
                ),
            ],
            options={
                "ordering": ["source", "row_number"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "org_id",
                    models.CharField(max_length=100),
                ),
            ],
            options={
                "ordering": ["location_id"],
            },
        ),
        migrations.CreateModel(
            name="SystemARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "normalized_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "imported_row_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_a_records",
                        to="reconciler.location",
                    ),
                ),
            ],
            options={
                "ordering": ["record_id"],
            },
        ),
        migrations.CreateModel(
            name="SystemBEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "normalized_record_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "normalized_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "imported_row_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_b_entries",
                        to="reconciler.location",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
